import type { ResumeData } from "@/lib/types";

export const RESUME_DATA: ResumeData = {
  name: "Sunny Li",
  initials: "SL",
  location: "Los Angeles, CA",
  locationLink: "https://www.google.com/maps/place/Los+Angeles,+CA",
  about: "Student. Product-minded engineer. Detail-obsessed",
  summary: (
    <>
      Excel in backend engineering, data modeling, and automation that prevents regressions and keeps systems easy to operate. Currently learning applied NLP/LLMs, and I’m also working on a product in the geospatial data domain!
    </>
  ),
  avatarUrl: "/sunnypfp.jpg",
  personalWebsiteUrl: "",
  contact: {
    email: "sunnyli@usc.edu",
    tel: "",
    social: [
      {
        name: "GitHub",
        url: "https://github.com/justsunli",
        icon: "github",
      },
      {
        name: "LinkedIn",
        url: "https://www.linkedin.com/in/justsunli/",
        icon: "linkedin",
      },
    ],
  },
  education: [
    {
      school: "University of Southern California",
      degree: "M.S. in Computer Science",
      start: "Jan 2025",
      end: "Dec 2026",
    },
    {
      school: "University of California, Los Angeles",
      degree: "B.S. in Computer Science",
      start: "Sep 2019",
      end: "Jun 2024",
    },
  ],
  work: [
    {
      company: "SLB",
      link: "https://www.slb.com/about/who-we-are/our-global-presence/slb-china",
      badges: ["Playwright", "TypeScript", "API Testing"],
      title: "Software Engineer Intern",
      start: "Jun 2025",
      end: "Aug 2025",
      description: (
        <ul className="list-inside list-disc space-y-1">
          <li>Revamped Wellbore Insights E2E automation with Playwright + TypeScript, hitting 88.6% endpoint coverage across 8 services and eliminating post-deploy API regressions.</li>
          <li>Built workflow-centric tests for upstream RCIS data and downstream services (4 shared services, 16 test workflows) to harden API contract reliability.</li>
          <li>Drove ~20% faster new-service adoption via reusable API wrappers, autogenerated benchmark assertions, and OpenAPI-typed contracts that reduced onboarding friction.</li>
        </ul>
      ),
    },
    {
      company: "BOC Fintech",
      link: "",
      badges: ["Java", "Spring Boot", "SQL Server", "Oracle"],
      title: "Software Engineer Intern",
      start: "Jul 2023",
      end: "Sep 2023",
      description: (
        <ul className="list-inside list-disc space-y-1">
          <li>Built compliance/risk platform backend in Spring Boot with SQL Server/Oracle to ingest and evaluate transaction streams, replacing manual review.</li>
          <li>Shipped 7 REST APIs for query/filter/export with schema contracts and predictable I/O semantics for downstream pipeline integration.</li>
          <li>Standardized Excel import/export via EasyExcel templates, reducing manual spreadsheet work ~40% and enabling consistent downstream ingestion.</li>
        </ul>
      ),
    },
  ],
  skills: [
    "Python",
    "C/C++",
    "Java",
    "TypeScript/JavaScript",
    "Spring Boot",
    "MySQL",
    "PostgreSQL",
    "DuckDB",
    "Git",
    "Docker",
  ],
  projects: [
    {
      title: "DuckDB Column Imprints for Zonemap Pruning",
      techStack: ["C++", "DuckDB", "SQL", "Benchmarking"],
      description:
        "Implemented 64-bit bitmap column imprints, integrated predicate-aware pruning, and benchmarked up to 84% speedups on selective TPC-H/DS queries.",
      link: {
        label: "GitHub",
        href: "https://github.com/justsunli/fall25-csci543-project2/tree/merged",
      },
    },
    {
      title: "FPGA Stopwatch",
      techStack: ["Verilog"],
      description: "Digital stopwatch implemented on a Basys 3 FPGA board.",
      link: {
        label: "GitHub",
        href: "https://github.com/justsunli/fpga-stopwatch",
      },
    },
    {
      title: "Game Glance",
      techStack: ["TypeScript", "React", "MySQL", "Go"],
      description: "Web app that aggregates and summarizes game reviews with LLM support.",
      link: {
        label: "GitHub",
        href: "https://github.com/justsunli/gameglance_frontend",
      },
    },
    {
      title: "Brewin#",
      techStack: ["Python"],
      description: "Object-oriented programming language built for COM SCI 131 coursework.",
      link: {
        label: "GitHub",
        href: "https://github.com/justsunli/interpreter-v4",
      },
    },
    {
      title: "On Track",
      techStack: ["JavaScript", "MongoDB"],
      description: "Smart course planner built by UCLA students for UCLA students.",
      link: {
        label: "GitHub",
        href: "https://github.com/AryamanLadha/onTrack-Backend",
      },
    },
    {
      title: "Rivalry Issue 2021",
      techStack: ["JavaScript", "React"],
      description: "Daily Bruin x Daily Trojan collaboration site for the annual football rivalry game.",
      link: {
        label: "Feature",
        href: "https://web.archive.org/web/20211209063816/https://dailytrojan.dailybruin.com/2021/",
      },
    },
    {
      title: "Graduation Issue 2021",
      techStack: ["JavaScript", "React"],
      description: "Daily Bruin 2021 graduation issue: \"Sunrise.\"",
      link: {
        label: "Feature",
        href: "https://special-features.dailybruin.com/2021/graduation-issue/",
      },
    },
    {
      title: "Origin of Plate Tectonics",
      techStack: ["Paper", "Geoscience"],
      description: "Review exploring mantle convection, lithospheric rheology, and buoyancy forces as tectonic drivers.",
      link: {
        label: "Paper",
        href: "https://drive.google.com/file/d/18tU7Z3qAI1_6cgwQDgeY0AE5fi59nI1A/view?usp=sharing",
      },
    },
    {
      title: "Structural Geology",
      techStack: ["Presentation", "Geoscience"],
      description: "Review of antithetic faults and displacement transfer across contractional relay zones.",
      link: {
        label: "Slides",
        href: "https://drive.google.com/file/d/1FFZgP4eNEiS-49K4eDpxOGw0PXFR9uxI/view?usp=sharing",
      },
    },

  ],
} as const;
